-- =========================================================================
-- NEW SHIFTS SCHEMA - SUPPORTS MULTIPLE CODES (e.g., two "N" shifts)
-- Core principle: shift_id is the ONLY unique identifier
-- code is display-only and may repeat across different shift templates
-- =========================================================================

-- Drop old schema
DROP TABLE IF EXISTS shift_scopes CASCADE;
DROP TABLE IF EXISTS shifts CASCADE;

-- Create SHIFTS table (NEW structure)
CREATE TABLE shifts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  
  -- Display code (e.g., "N", "D", "E") - NOT UNIQUE, can repeat
  code TEXT NOT NULL,
  
  -- Optional label for disambiguation (e.g., "Night (12h)" or "Night (12.5h)")
  label TEXT,
  
  -- Time boundaries (optional - not all shifts have specific times)
  start_time TIME,
  end_time TIME,
  
  -- Hours attributed to this shift
  hours_value DECIMAL(5, 2) NOT NULL DEFAULT 0,
  
  -- Day or night classification
  day_or_night TEXT CHECK (day_or_night IN ('day', 'night')),
  
  -- Staff group eligibility (comma-separated: "NA", "Nurse", "NA,Nurse")
  allowed_staff_groups TEXT NOT NULL DEFAULT 'NA,Nurse',
  
  -- Scope flags: where this shift is available
  allow_requests BOOLEAN DEFAULT TRUE,
  allow_draft BOOLEAN DEFAULT TRUE,
  allow_post_publish BOOLEAN DEFAULT TRUE,
  
  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  -- Prevent accidental exact duplicates
  UNIQUE(code, hours_value, allowed_staff_groups)
);

-- Insert sample data: two "N" shifts for different staff groups
INSERT INTO shifts (code, label, start_time, end_time, hours_value, day_or_night, allowed_staff_groups, allow_requests)
VALUES
  -- Night shift for NAs: 12 hours
  ('N', 'Night (12h)', '21:00:00', '09:00:00', 12.0, 'night', 'NA', TRUE),
  
  -- Night shift for Nurses: 12.5 hours
  ('N', 'Night (12.5h)', '21:00:00', '09:00:00', 12.5, 'night', 'Nurse', TRUE),
  
  -- Day shifts for both groups
  ('D', 'Day', '08:00:00', '20:00:00', 12.0, 'day', 'NA,Nurse', TRUE),
  ('LD', 'Long Day', '07:00:00', '20:00:00', 13.0, 'day', 'NA,Nurse', TRUE),
  
  -- Other shifts
  ('E', 'Early', '06:00:00', '14:00:00', 8.0, 'day', 'NA,Nurse', TRUE),
  ('L', 'Late', '14:00:00', '22:00:00', 8.0, 'day', 'NA,Nurse', TRUE),
  ('O', 'Off', NULL, NULL, 0.0, 'day', 'NA,Nurse', TRUE);

-- Create indexes
CREATE INDEX idx_shifts_code ON shifts(code);
CREATE INDEX idx_shifts_allowed_groups ON shifts(allowed_staff_groups);
CREATE INDEX idx_shifts_requests ON shifts(allow_requests) WHERE allow_requests = TRUE;

-- Verify
SELECT 
  id,
  code,
  label,
  hours_value,
  allowed_staff_groups,
  allow_requests
FROM shifts
ORDER BY code, hours_value;
